name: build

on: workflow_dispatch

jobs:
    build_gameboy:
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
        
          - name: Set Up RGBDS
            uses: gbdev/rgbds@v1
            
          - name: Build GBC Game
            run: |
                rgbasm -o main.o source/main.asm
                rgblink -o main.gbc main.o
                rgbfix -v -p 0 main.gbc
                
          - name: Upload Artifact
            uses: actions/upload-artifact@v3
            with:
                name: Game
                path: main.gbc