name: build

on: workflow_dispatch

jobs:
    build_gameboy:
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
        
          - name: Set Up RGBDS
            run: pacman -S rgbds
            
          - name: Build GBC Game
            run: |
              rgbasm -o game.o source/main.asm
              rgblink -o game.gb game.o
              rgbfix -v game.gb
            
          - name: Upload Artifact
            uses: actions/upload-artifact@v3
            with:
                name: Game
                path: main.gb