name: build

on: workflow_dispatch

jobs:
    build_gameboy:
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
        
          - name: Set Up RGBDS
            run: |
                make
                sudo make install
            
          - name: Build GB Game
            run: |
                rgbasm -o main.o source/main.asm
                rgblink -o main.gb main.o
                rgbfix -v -p 0 main.gb
                
          - name: Upload Artifact
            uses: actions/upload-artifact@v3
            with:
                name: Game
                path: main.gb