name: build

on: workflow_dispatch

jobs:
    build_gameboy:
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
        
          - name: Set Up RGBDS
            uses: gbdev/rgbds@v0.6.1
            
          - name: Build GBC Game
            run: rgbasm source/main.asm main.gb
            
          - name: Upload Artifact
            uses: actions/upload-artifact@v3
            with:
                name: Game
                path: main.gb